name: Continuous Integration and Deployment

on:
  push:
    -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - nane: Setup .Net 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'  

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore